spring:
  application:
    name: digital-marketing-agency-backend

  data:
    mongodb:
      host: localhost
      port: 27017
      database: digital_marketing_agency

server:
  port: 8080

  jwt:
    secret: 12345678901234567890123456789012
    expiration: 86400000